# Generated by Django 5.0.6 on 2025-07-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_flashcard_tags_note_tags_question_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags/groups associated with this user', related_name='user_profiles', to='core.tag'),
        ),
    ]
