# Generated by Django 5.0.6 on 2025-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags/groups assigned to this user', to='core.tag'),
        ),
    ]
