# Generated by Django 5.0.6 on 2025-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_tags_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college_type',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1st_year', '1st Year MBBS'), ('2nd_year', '2nd Year MBBS'), ('3rd_year', '3rd Year MBBS'), ('4th_year', '4th Year MBBS'), ('final_year', '5th Year MBBS (Final)'), ('graduate', 'Graduate')], max_length=20),
        ),
    ]
